Merge develop - Foundry edition (#385)
* Introduce Foundry testing framework (#7886)

* core/config/v2: support multiple TOML config files (#7899)

* Add Sonar exclussions for autogenerated files (#7906)

* Disable Keeper Tests Temporarily (#7915)

* .github: ensure failure log artifacts are uploaded (#7916)

* [DR-OCR] Two aggregation methods (mode and median) (#7889)

* docs: fix/improve TOML config docs (#7910)

* fix: foundry merge

* Delete ccip-contracts.yml & fix CI

* fix: module

* chore: fix merge issues

* fix ci

Co-authored-by: Jordan Krage <jmank88@gmail.com>
Co-authored-by: chudilka1 <yepishevsanya@gmail.com>
Co-authored-by: Adam Hamrick <adam.hamrick@smartcontract.com>
Co-authored-by: Bolek Kulbabinski <1416262+bolekk@users.noreply.github.com>

diff --git a/contracts/scripts/ccip_public_abi_check b/contracts/scripts/ccip_public_abi_check
--- a/contracts/scripts/ccip_public_abi_check
+++ b/contracts/scripts/ccip_public_abi_check
@@ -2,7 +2,7 @@
 
 set -e
 
-FILES="./contracts/src/v0.8/ccip/test/publicABI/*"
+FILES="./src/v0.8/ccip/test/publicABI/*"
 
 for f in $FILES
 do
@@ -14,11 +14,11 @@ do
   actualAbi=$( forge inspect $fileName methods | tr -d " \t\n\r" )
 
   if [[ "$expectedAbi" != "$actualAbi" ]]; then
-    printf "$fileName ABI does not match expected ABI. Fixing...\n"
-    make ccip-abi-generate c=$fileName
-    printf "Fixed.\n"
+    printf "ERROR: $fileName ABI does not match expected ABI. Try running this command:\n\n"
+    printf "make ccip-abi-fix\n\n"
+    exit 1
   fi
 
 done
 
-echo "ABI fix successful, don't forget to commit!"
+echo "ABI check successful"
