revert entrypoint changes

diff --git a/integration-tests/scripts/entrypoint b/integration-tests/scripts/entrypoint
--- a/integration-tests/scripts/entrypoint
+++ b/integration-tests/scripts/entrypoint
@@ -21,11 +21,11 @@ exit_code=$?
 
 echo "Test exit code: ${exit_code}"
 
-if [ $exit_code -eq 1 ]; then
-  exit 5
+# 3 is the code for an interrupted test, we only want to restart the test when the test is interrupted and in a state
+# that it can recover from. Otherwise we mark the test as "passed" as far as K8s is concerned so it doesn't restart it.
+if [ $exit_code -eq 3 ]; then
+  exit 1  # Exiting with non-zero status to trigger pod restart
 fi
-
-exit $exit_code
 
 # Sleep for the amount of time provided by the POST_RUN_SLEEP env var
 upload_to_slack() {
